Django_Project/api/urls.py
from django.urls import path
from .views import (
    CategoryListView, ProductListView, ProductDetailView,
    ProductCreateView, ProductUpdateView, ProductDeleteView,
    ProductListCreateView, ProductRetrieveUpdateDeleteView
)

app_name = 'api'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # path('products/', ProductListView.as_view(), name='product_list'),
    # path('products/<int:id>/', ProductDetailView.as_view(), name='product_detail'),
    # path('add_product/', ProductCreateView.as_view(), name='add_product'),
    # path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    # path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('products/', ProductListCreateView.as_view(), name='product_list_create'),
    path('products/<int:pk>/', ProductRetrieveUpdateDeleteView.as_view(), name='product_get_update_delete'),
]

Django_Project/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from core.views import (
    ProductListView, ProductCreateView, ProductUpdateView,
    ProductDetailView, ProductDeleteView
)

app_name = 'core'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('product/<int:product_pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('update_product/<int:product_pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:product_pk>/', ProductDeleteView.as_view(), name='delete_product'),
]

Django_Project/test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Project/user/urls.py
from django.urls import path, reverse_lazy
from user.views import UserRegisterView, UserLoginView, UserProfileView, activate_account
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('user:login')), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('activate/<int:uid>/<str:token>/', activate_account, name='activate')
]

Django_Project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'navbar.html' %}
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        <hr>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>

Django_Project/templates/navbar.html
<nav class="navbar mb-4 navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:about' %}">About</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user }}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a></li>
                    <li>
                        <form method="POST" action="{% url 'user:logout' %}">
                            {% csrf_token %}
                            <button class="dropdown-item">Logout</button>
                        </form>
                    </li>
                  </ul>
                </li>
            {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
                </li>
            {% endif %}

          </ul>
          <form class="d-flex" role="search" action="{% url 'core:index' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}"/>
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>