Django_Project/api/urls.py
from django.urls import path
from .views import (
    CategoryListView, ProductListView, ProductDetailView,
    ProductCreateView, ProductUpdateView, ProductDeleteView,
    ProductListCreateView, ProductRetrieveUpdateDeleteView
)

app_name = 'api'

urlpatterns = [
    path('categories/', CategoryListView.as_view(), name='category_list'),
    # path('products/', ProductListView.as_view(), name='product_list'),
    # path('products/<int:id>/', ProductDetailView.as_view(), name='product_detail'),
    # path('add_product/', ProductCreateView.as_view(), name='add_product'),
    # path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    # path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('products/', ProductListCreateView.as_view(), name='product_list_create'),
    path('products/<int:pk>/', ProductRetrieveUpdateDeleteView.as_view(), name='product_get_update_delete'),
]

Django_Project/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from core.views import (
    ProductListView, ProductCreateView, ProductUpdateView,
    ProductDetailView, ProductDeleteView
)

app_name = 'core'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('product/<int:product_pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('add_product/', ProductCreateView.as_view(), name='add_product'),
    path('update_product/<int:product_pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:product_pk>/', ProductDeleteView.as_view(), name='delete_product'),
]

Django_Project/test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('user/', include('user.urls', namespace='user')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Project/core/models.py
from django.db import models
from core.managers import BaseManager

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        db_table = 'categories'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.IntegerField()
    available = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)
    views = models.PositiveIntegerField(verbose_name="ნახვები", default=0)

    objects = BaseManager()

    class Meta:
        db_table = 'products'

    def __str__(self):
        return self.name

Django_Project/core/forms.py
from django import forms
from core.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ('available', 'views')

Django_Project/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.db.models import Q

from core.forms import ProductForm
from core.models import Product, Category
from django.views.generic import (
    ListView, CreateView, UpdateView,
    DetailView, DeleteView
)

class ProductListView(ListView):
    model = Product
    template_name = 'index.html'
    context_object_name = 'products'
    # queryset = Product.objects.all().select_related('category')
    # ordering = ['-created_at']
    # paginate_by = 3

    def get_queryset(self):
        products = Product.objects.all().select_related('category').order_by('-created_at')

        search_query = self.request.GET.get('q')
        category_name = self.request.GET.get('category')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        if search_query:
            products = products.filter(Q(name__icontains=search_query) | Q(description__icontains=search_query))

        if category_name:
            products = products.filter(category__name=category_name)

        if min_price:
            products = products.filter(price__gte=min_price)

        if max_price:
            products = products.filter(price__lte=max_price)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_products'] = self.get_queryset().count()
        context['categories'] = Category.objects.all()
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'
    pk_url_kwarg = 'product_pk'

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'add_product.html'
    success_url = reverse_lazy('core:index')
    login_url = 'user:login'

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'update_product.html'
    pk_url_kwarg = 'product_pk'

    def get_success_url(self):
        return reverse_lazy('core:product_detail', kwargs={'product_pk': self.object.pk})

class ProductDeleteView(DeleteView):
    model = Product
    pk_url_kwarg = 'product_pk'
    success_url = reverse_lazy('core:index')

# def index(request):
#     # return HttpResponse("<h1>Hello World!</h1>")
#     products = Product.objects.values()
#     return JsonResponse({"products": list(products)})

# def index(request):
#     products = Product.objects.all().select_related('category')
#     total_products = products.count()
#
#     context = {
#         'products': products,
#         'total_products': total_products,
#     }
#
#     return render(request, 'index.html', context)

# def product_detail(request, product_pk):
#     product = get_object_or_404(Product, pk=product_pk)
#     return render(request, 'product_detail.html', {'product': product})

# def add_product(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#
#         if form.is_valid():
#             form.save()
#             return redirect("core:index")
#     else:
#         form = ProductForm()
#     return render(request, 'add_product.html', {'form': form})

# def update_product(request, product_pk):
#     product = get_object_or_404(Product, pk=product_pk)
#     if request.method == 'POST':
#         form = ProductForm(request.POST, instance=product)
#
#         if form.is_valid():
#             form.save()
#             return redirect("core:product_detail", product_pk=product_pk)
#     else:
#         form = ProductForm(instance=product)
#     return render(request, 'update_product.html', {'form': form})

# def delete_product(request, product_pk):
#     product = get_object_or_404(Product, pk=product_pk)
#     if request.method == "POST":
#         product.delete()
#         return redirect("core:index")
#     return redirect("core:index")

# def about(request):
#     return render(request, 'about.html')

# class AboutView(TemplateView):
#     template_name = 'about.html'

Django_Project/core/templates/about.html
{% extends 'base.html' %}

{% block title %}About Page{% endblock %}
{% block content %}
    <h2>This is an about page</h2>
    <hr>
    <a href="{% url 'core:index' %}">Home Page</a>
{% endblock %}

Django_Project/core/templates/add_product.html
{% extends 'base.html' %}

{% load crispy_forms_tags%}
{% load crispy_forms_filters %}

{% block title %} Add product {% endblock %}
{% block content %}
    <form class="custom-class" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success mb-3">Add Product</button>
    </form>
{% endblock %}

Django_Project/core/templates/index.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <h1>Welcome to home page</h1>
    <div class="row">
        <div class="col-md-2">
            <form action="">
                <select class="form-select" name="category">
                    <option value="">All Categories</option>
                    {% for category in categories %}
                        <option value="{{ category.name }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
                <input class="form-control mt-3" type="number" name="min_price" placeholder="Min Price" value="{{ request.GET.min_price }}">
                <input class="form-control mt-2" type="number" name="max_price" placeholder="Max Price" value="{{ request.GET.max_price }}">
                <button class="btn btn-primary mt-4">Filter</button>
            </form>
        </div>
        <div class="col-md-10">
            <h4>Total Products: {{ total_products }}</h4>
                <div class="row d-flex justify-content-between">
                    {% for product in products %}
                        <div class="card p-2 mb-3" style="width: 18rem;">
                          {% if product.image %}
                              <img src="{{ product.image.url }}" class="card-img-top" style="height: 250px" alt="...">
                          {% endif %}
                          <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <a href="{% url 'core:product_detail' product.pk %}" class="btn btn-primary">More Info</a>
                          </div>
                        </div>
                    {% endfor %}
                </div>
            {% if is_paginated %}
                <nav aria-label="Page navigation example">
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">&laquo; First</a></li>
                        <li class="page-item disabled"><a class="page-link">Previous</a></li>
                    {% endif %}
                    {% for num in paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link">{{ num }}</a></li>
                        {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}">Last &raquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link">Next</a></li>
                        <li class="page-item disabled"><a class="page-link">Last &raquo;</a></li>
                    {% endif %}
                  </ul>
                </nav>
            {% endif %}
        </div>
    </div>
    <hr>
    <a class="btn btn-primary" href="{% url 'core:add_product' %}">Add New Product</a>
{% endblock %}

Django_Project/core/templates/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}
{% block content %}
    {% if product.image %}
        <img style="width: 200px" src="{{ product.image.url }}" alt="">
    {% endif %}
    <h3>Product: {{ product.name }}</h3>
    <p>Quantity: {{ product.quantity }}</p>
    <p>Price: {{ product.price }}</p>
    <small>Category: {{ product.category.name }}</small>
    <hr>
    <a class="btn btn-success mb-3" href="{% url 'core:update_product' product.pk %}">Update</a>
    <form action="{% url 'core:delete_product' product.pk %}" method="POST" onsubmit="return confirm('Are you sure you want to delete?')">
        {% csrf_token %}
        <button class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

Django_Project/core/templates/update_product.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %} Update Product {% endblock %}

{% block content %}
    <form class="custom-class" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success mb-3">Update</button>
    </form>
{% endblock %}